### ISSUE TITLE
Issues with email address render

### ISSUE THREAD

**Issue by mr-kashif** [emailage/Emailage_Go#15]
Hi!

On response form ``EmailOnlyScore`` API, I'm receiving an ill-formatted email address for 
eg:- ``person@organization.com`` prints as ``person%40organization.com``

<img width="400" alt="Screenshot 2019-08-08 at 12 26 10 PM" src="https://user-images.githubusercontent.com/24528125/62681742-05a0a780-b9d8-11e9-986c-8e26923294b8.png">
<img width="287" alt="Screenshot 2019-08-08 at 12 27 53 PM" src="https://user-images.githubusercontent.com/24528125/62681740-05081100-b9d8-11e9-86f6-84b72b0db6ce.png">

**Comment by martinkduncan** [comment]
Thanks! I will take a look at this.

**Comment by martinkduncan** [comment]
The code for this has been updated.  The Module will be updated shortly.

**Comment by martinkduncan** [comment]
Module is updated, can you confirm that your issue has been resolved?

**Comment by mr-kashif** [comment]
It's resolved now. Thank you.
